import Foundation
import Amplify
import AWSS3StoragePlugin
internal import Combine

// Note: Ensure `Post` model is available via Amplify Gen 2 generation
// usually it is `Post` struct generated by `npx ampx sandbox`
// But in Swift, we use the `Model` provided by the library or dynamic access.
// For now, we assume a `Post` model exists or we use the untyped approach if needed.
// However, typically `Amplify.API` works with `Model`.
// Since we don't have the generated models in this file system, I will write generic code
// or assume the user has generated them.

class UploadService: ObservableObject {
    @Published var uploadProgress: Double = 0.0
    @Published var isUploading = false
    @Published var uploadError: String?
    
    func uploadVideo(fileURL: URL, team: String, sport: String, description: String) async throws {
        await MainActor.run {
            isUploading = true
            uploadProgress = 0
        }
        
        let videoKey = "media/\(UUID().uuidString).mp4"
        
        do {
            // 1. Upload to S3 (Using Path API)
            // Fix: 'path' expects StoragePath (use .fromString), and parameter is 'local' not 'body'
            let uploadTask = Amplify.Storage.uploadFile(
                path: .fromString(videoKey),
                local: fileURL
            )
            
            for await progress in await uploadTask.progress {
                await MainActor.run {
                    self.uploadProgress = progress.fractionCompleted
                }
            }
            
            let result = try await uploadTask.value
            print("Upload complete: \(result)")
            
            // 2. Create Metadata in DynamoDB
            // 2. Create Metadata in DynamoDB
            let post = Post(
                videoURL: videoKey,
                teamTag: team,
                sportTag: sport,
                timestamp: Temporal.DateTime.now(),
                description: description
            )
            try await Amplify.API.mutate(request: .create(post))
            
            print("Metadata saved")
            
        } catch {
            await MainActor.run {
                self.uploadError = error.localizedDescription
            }
            throw error
        }
        
        await MainActor.run {
            isUploading = false
        }
    }
}
